### ISSUE TITLE
No schema.json in glance

### ISSUE THREAD

**Issue by edtubillara** [dev-sec/openstack-baseline#12]
Hi,
I cannot find the schema.json file configuration in glance and so the checks are failing for that. I am running Newton. I submitted a pull request to see if it was okay to make the list of config files configurable through attributes:
https://github.com/chef-partners/inspec-openstack-security/pull/11

**Comment by jjasghar** [comment]
Seem reasonable. Can you fill out #11 farther to see what you'd like to do across the board?

**Comment by edtubillara** [comment]
Cool, what do you mean by filling it out farther? Should I fill the commit message with more information?

**Comment by jjasghar** [comment]
Oh I read this wrong. I thought you found a missing `schema.json` for every control. Yep, this seems very reasonable, I'll go ahead and merge it.

**Comment by edtubillara** [comment]
Thanks!
